### ISSUE TITLE
Add a better description for problem 5

### ISSUE THREAD

**Issue by emancu** [pgr0ss/elixir_experience#20]
The current description is

> Write a function palindrome? that checks if a given string is a palindrome, A palindrome is a word, phrase, number, or other sequence of characters which reads the same backward or forward. e.g

The description is not accurate, it should point out that the user must ignore spaces and every non word character.

Look at the tests
```elixir
assert palindrome?(\"A man, a plan, a canal, Panama!\") == true
assert palindrome?(\"Amor, Roma\") == true
assert palindrome?(\"'Ma,' Jerome raps pot top, 'Spare more jam!'\") == true
```

**Comment by pgr0ss** [comment]
Good point. Want to submit a pull request with an updated description?

**Comment by pgr0ss** [comment]
Thanks for the contribution!
