### ISSUE TITLE
Create custom CSS

### ISSUE THREAD

**Issue by lpil** [pgr0ss/elixir_experience#22]
Hello!

I'd like to make some additions to the CSS of this project, but there doesn't seem to be any formal structure or front end build process.

Are there any plans here? Given I know nothing of your deployment process, would adding a node.js based built tool cause complications?

If you wish to stick to old fashioned CSS, would you be happy to loading bootstrap and the custom CSS in two requests? Sadly vim reeeeeeally does not enjoy editing a file that starts with a large minified CSS library on the first line, so it'd be nice to have the vendor stuff in another file.

Thanks,
Louis

**Comment by lpil** [comment]
Here are some notes on improving the CSS

* Style the input box
* Align profile icon in header
* Fix the two tone background on `code` and `pre` caused by the JS colouring library clashing with bootstrap
* Fix title in header wrapping on mobiles
* Fix problems table not working on mobiles

**Comment by pgr0ss** [comment]
I haven't really thought much about the front end build process. I guess for now, I'd prefer to stick to old fashioned CSS. I think two requests for CSS is fine.

FYI, the deployment process is just building and running docker containers:
https://github.com/pgr0ss/elixir_experience/blob/5a7c9fe6e8a34448e60d7780343a82aa19b3a896/start.sh

**Comment by lpil** [comment]
My experience with docker is extremely limited, so I'll leave that to you for now. Definitely something on my learning list though :)
