### ISSUE TITLE
Consider replacing problem descriptions on problems list with problem titles. 

### ISSUE THREAD

**Issue by lpil** [pgr0ss/elixir_experience#23]
Hello!

I propose we swap the descriptions on this table (on the home page) with titles for the following reasons:
- Descriptions are too long, and get clipped, making it generally not possible to read.
- Descriptions beginnings are very repetitive, and when this is all we can see we gain no meaningful information on the problems.
- Descriptions contain markdown, which is not rendered on this table.

And it just looks a bit busy ;P

Cheers,
Louis

**Comment by pgr0ss** [comment]
I think this make sense.
