### ISSUE TITLE
Add a real code editor

### ISSUE THREAD

**Issue by lpil** [pgr0ss/elixir_experience#24]
It'd be good to support indenting with tabs, highlighting, etc.

I imagine there's a pre-built JS library for this.

**Comment by pgr0ss** [comment]
:+1:

**Comment by doomspork** [comment]
I can take a shot at incorporating [Ace](https://github.com/ajaxorg/ace) if no one else is already working on this.

**Comment by pgr0ss** [comment]
Go for it!

**Comment by lpil** [comment]
Ace was what I was going to have a go with if I found the time. Looks good! :)

**Comment by doomspork** [comment]
@lpil if you want to take a shot at integrating Ace feel free, I've suddenly become swamped at work so it'll be a bit before I can focus my attention on this again.

**Comment by lpil** [comment]
OK, thanks for letting me know. I don't know if I have time, but I might take a shot at it.
