### ISSUE TITLE
Inform user if the docker image is being downloaded the first time tests are run

### ISSUE THREAD

**Issue by lpil** [pgr0ss/elixir_experience#32]
Perhaps add a note if it's expected behaviour. The lack of feedback made me think that it had crashed silently.

**Comment by pgr0ss** [comment]
We can probably make it clearer that it's downloading the docker image.

**Comment by lpil** [comment]
Ah, so that's what it's doing. Makes sense :)

**Comment by pgr0ss** [comment]
I solved this a different way. I added a `mix docker.pull` and instructions to run that before running the app or tests: https://github.com/pgr0ss/elixir_experience/commit/9a6826f513dcb6bff963a87bbb1ec934e77c99dd

**Comment by lpil** [comment]
Good solution. Thanks!
